# Generated by Django 5.1.1 on 2024-09-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_cover_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
    ]
